//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taller2Razor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuario
    {
        public int IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string Email { get; set; }
        public Nullable<int> RolUsuario { get; set; }
    
        public virtual tbRol tbRol { get; set; }
    }
}
